### PR TITLE
fix: Updated `ioredis` instrumentation to handle breakage of errors when using `.pipeline`.

### LINKED ISSUE #3448: Redis instrumentation for ioredis using pipelines creates uncatchable, unhandled rejected promises starting with v13.2.0 crashing the process
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Starting with newrelic v13.2.0, using ioredis instrumentation with pipelines that have a failed command cause the process to crash with an unhandled Promise rejection. The Promise appears to not be `.catch()`able anywhere within my userland code.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

Using `new Redis().pipeline().set('key1', []).exec()`, which has an invalid `set` command, should not crash the process with an unhandled Promise rejection.

## Steps to Reproduce

I've created a minimal reproduction at https://github.com/KevinEady/newrelic-redis-bug-repro which supports testing any given `newrelic` package version, but the gist is:

```js
const redis = new Redis("redis:6379");

try {
    const res = await redis.pipeline()
        .set('key1', [])
        .exec();

    console.log("Done!", res);
} catch (e) {
    console.error("Caught pipeline error:", e);
}
``` 

The `pipeline().exec()` call resolves successfully with an array of errors:
```js
Done! [
  [
    ReplyError: ERR wrong number of arguments for 'set' command
        at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
      command: [Object]
    }
  ]
]
```

But the process gets an uncaught Promise rejection:
```
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

ReplyError: ERR wrong number of arguments for 'set' command
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'set', args: [ 'key1' ] }
}

Node.js v20.19.5
```

Adding a callback to `.set()` still causes the unhandled Promise rejection. 

This does **not** occur in newrelic v13.1.0 or if newrelic instrumentation is disabled.

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

- Node.js v20.19.5
- NewRelic >=v13.2.0
- Redis 6.2.20

## Additional context

- Maybe introduced via https://github.com/newrelic/node-newrelic/pull/3207 ?

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

### PR DESCRIPTION
**Pull request by bizob2828**
## Description

This was a fun one and I explain the fix in the comments of `lib/subscribers/ioredis/index.js`.  tl;dr: ioredis breaks promise chains and we expose that when using `tracePromise`.  
We didn't catch this when we migrated ioredis because we lacked both error tests and pipeline tests. This PR adds those to avoid future regressions.

## Related Links
Closes #3448.

### CODE REVIEW

File: lib/subscribers/ioredis/index.js [hunk 1]
```diff
@@ -21,6 +22,29 @@ class IoRedisSubscriber extends DbOperationSubscriber {
...
+   * Same code as `lib/subscribers/openai/base.js` but being used for a different reason.
+   * For the standard `await redis.<cmd>(..args)`, tracePromise works just fine. It's to appease the `redis.pipeline().<cmd>(...args).exec()` case.
+   * When commands are queued, a `.then` and `.catch` handler is attached, but don't queue up the result of that, but instead just queue up the command. They've broken the promise chain and since `tracePromise` just continues the chain, this will cause an unhandledRejection.
+   * see: https://github.com/redis/ioredis/blob/d5f5b407bd1287fd86d2ca5df7a10c50c9702305/lib/Pipeline.ts#L218
+   *
+   * @param {object} data the data associated with the `end` event
+   */
+  end(data) {
+    const promise = data?.result
+    if (!promise.then) {
```
Comment (jsumners-nr) [inline lib/subscribers/ioredis/index.js]:
```suggestion
    if (typeof promise.then !== 'function') {
```

File: test/versioned/ioredis/ioredis.test.js [hunk 2]
```diff
@@ -210,4 +210,60 @@ test('ioredis instrumentation', async (t) => {
       transaction.end()
     })
   })
+
+  // TODO: add something in a promise chain to verify this is working as expected
```
Comment (jsumners-nr) [inline test/versioned/ioredis/ioredis.test.js]: Is this TODO left over, or an actual task for later?

File: lib/subscribers/ioredis/index.js [hunk 3]
```diff
@@ -10,6 +10,7 @@ const stringify = require('json-stringify-safe')
 class IoRedisSubscriber extends DbOperationSubscriber {
   constructor({ agent, logger }) {
     super({ agent, logger, packageName: 'ioredis', channelName: 'nr_sendCommand', system: 'Redis' })
+    // this.events = ['asyncEnd', 'end']
     this.events = ['asyncEnd']
```
Comment (jsumners-nr) [inline lib/subscribers/ioredis/index.js]:
```suggestion
    this.events = ['asyncEnd']
```

Comment (bizob2828) [reply lib/subscribers/ioredis/index.js]: yea sorry, i had code for testing, i just pushed up the real stuff
