### PR TITLE
#1238 failed to connect redis on startup resolved, handled 'opts' and…

### LINKED ISSUE #1238: Issue: Failed to connect to Redis on startup.
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Encounter an issue while starting the app. It says, failed to connect to Redis. There is a TypeError: cannot read the property of undefined (reading 'port').

## Expected Behavior
Running *npm start* must have started the app without any error.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
Add newrelic.js file to ROOT folder.
*npm i newrelic*
Run the app.
There is a MongoDB connection and a Redis connection inside the app

## Your Environment

* ex: Browser name and version: NA
* ex: Node version:  12.22.8 || 13.14.0 || 16.14.2 || 17.3.0
* ex: Operating System and version:

### PR DESCRIPTION
**Pull request by RAshidAZ**
… when 'socket' is undefined

## Proposed Release Notes
 * Added defensive code in redis v4 instrumentation to check for `opts.socket` first before evaluating `opts.socket.path`.
 
## Links
Closes #1238

### CODE REVIEW

File: lib/instrumentation/@node-redis/client.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ module.exports = function initialize(agent, redis, moduleName, shim) {
   function getRedisParams(opts) {
     return {
       host: (opts.socket && opts.socket.host) || 'localhost',
-      port_path_or_id: (opts.socket && opts.socket.path) || opts.socket.port || '6379',
+      port_path_or_id: (opts.socket && opts.socket.path) || (opts.socket && opts.socket.port) || '6379',
```
Comment (bizob2828) [inline lib/instrumentation/@node-redis/client.js:57]:
```suggestion
      port_path_or_id: (opts.socket && opts.socket.path || opts.socket.port) || '6379',
```

**Comment by bizob2828** [comment]
@RAshidAZ you also need to sign the CLA please

**Comment by RAshidAZ** [comment]
> @RAshidAZ you also need to sign the CLA please

Hi @bizob2828, I have already signed in to the CLA yesterday.

**Comment by bizob2828** [comment]
> > @RAshidAZ you also need to sign the CLA please
> 
> Hi @bizob2828, I have already signed in to the CLA yesterday.

It looks like it's because your first commit was with a different username.  I'd either rebase and squash that commit or also sign the CLA for @r0a0ith

**Review by bizob2828 — APPROVED** [review]
Thanks for the fix @RAshidAZ!

**Comment by RAshidAZ** [comment]
> Thanks for the fix @RAshidAZ!

You're welcome @bizob2828 .
