### PR TITLE
fix: Fixed undici/fetch instrumentation to properly assign the parent-id portion of the `traceparent` header on outgoing requests to the active http external span id

### LINKED ISSUE #2950: traceparent has incorrect parent id when using undici/fetch
## Description
A customer reported an anomaly with traces and how the downstream entity was being represented as a sibling of the upstream http call not a child.

## Steps to Reproduce

Make a fetch/undici request to a downstream application.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

The parent id of the downstream span should be the id of the http external call.

Image

## Actual Result

The parent id is the parent of the upstream http call, not the http call itself

Image

## Additional context
This appears to be because we're setting the DT headers before the external segment is getting created in undici. We're also missing some assertions on the validity of the traceparent for undici, http, and message queue producers.

### PR DESCRIPTION
**Pull request by bizob2828**
## Description

See details in #2950 as to why. This PR adds more tests to the relevant places that inject `traceparent` to ensure the parts are the expected values.

## Related Issues
Closes #2950

### CODE REVIEW

File: lib/instrumentation/undici.js [hunk 1]
```diff
@@ -136,8 +136,8 @@ function requestCreateHook(shim, { request }) {
   }
 
   try {
-    addDTHeaders({ transaction, config, request })
     createExternalSegment({ shim, request, segment })
+    addDTHeaders({ transaction, config, request })
```
Comment (jsumners-nr) [inline lib/instrumentation/undici.js:140]: So there's some side effects in these function such that ordering of their invocation matters in order to get the correct parent id attached to the new request?

**Review by jsumners-nr — APPROVED** [review]

File: lib/instrumentation/undici.js (hunk 1 above)
Comment (bizob2828) [reply lib/instrumentation/undici.js:140]: yes. in `createExternalSegment` we create the segment and set it as active, then assign the outgoing w3c headers. Before we were setting outgoing w3c headers so it was on the parent span of the undici/fetch request. The versioned test proves this, if you swap the order the test fails
