### PR TITLE
chore: Fixed redis legacy test suite

### LINKED ISSUE #3073: Investigate `redis` instrumenation in regard to v5.0.0
https://github.com/redis/node-redis/releases/tag/redis%405.0.0 was released on 2025-04-30. It seems to have changed some things that caused CI failure:

https://github.com/newrelic/node-newrelic/actions/runs/14772905878/job/41475967148#step:7:169

We need to investigate if there is anything that we need to update and perform any such work. It's possible that #3072 is all that needs to be done.

### PR DESCRIPTION
**Pull request by jsumners-nr**
This PR resolves #3073. Our legacy tests were actually incorrect. The legacy mode _requires_ callbacks. Our tests were setting the client to legacy mode and then accessing the non-legacy mode through the `.v4` client.

### CODE REVIEW

File: test/versioned/redis/newrelic.js [hunk 1]
```diff
@@ -16,6 +16,7 @@ exports.config = {
     detect_docker: false
   },
   logging: {
-    enabled: false
+    enabled: false,
+    level: 'trace'
```
Comment (mrickard) [inline test/versioned/redis/newrelic.js:20]: Does `trace` matter here if logging isn't enabled?

Comment (jsumners-nr) [reply test/versioned/redis/newrelic.js:20]: No. It was used while I was debugging things. But it doesn't hurt to leave it for future use.

File: lib/instrumentation/redis.js [hunk 2]
```diff
@@ -12,8 +12,23 @@ const {
 } = require('../shim/specs')
 
 module.exports = function initialize(_agent, redis, _moduleName, shim) {
+  const version = Number(shim.pkgVersion.split('.').shift())
```
Comment (bizob2828) [inline lib/instrumentation/redis.js:15]: I'm not sure I understand this code.  The instrumentation worked just fine, it was just that the legacy mode wasn't using callbacks.

File: test/versioned/redis/redis-v4-legacy-mode.test.js [hunk 3]
```diff
@@ -16,20 +16,48 @@ const { checkMetrics } = require('./utils')
 // Indicates unique database in Redis. 0-15 supported.
 const DB_INDEX = 2
 
+const pkg = require('redis/package.json')
+const redisVersion = Number(pkg.version.split('.').shift())
```
Comment (bizob2828) [inline test/versioned/redis/redis-v4-legacy-mode.test.js:20]: like the instrumentation, I would update to use `semver` to check the version

File: test/versioned/redis/redis-v4-legacy-mode.test.js [hunk 4]
```diff
@@ -16,20 +16,48 @@ const { checkMetrics } = require('./utils')
...
+      // We also need the `.select` method that is not carried over.
+      const select = client.select.bind(client)
+
+      client = client.legacy()
+      client.close = close
+      client.select = (idx, callback) => {
+        select(idx).then(() => { callback() }).catch(error => callback(error))
+      }
+    } else {
+      client = redis.createClient({
```
Comment (bizob2828) [inline test/versioned/redis/redis-v4-legacy-mode.test.js:51]: I think I wrote this suite and these updates are def valid but the issue we had seen from a customer was also that the v4 interface wasn't working. Now that you refactored this, there are no tests for the v4 interface in legacy mode

Comment (bizob2828) [reply test/versioned/redis/redis-v4-legacy-mode.test.js:51]: Here's that PR https://github.com/newrelic/node-newrelic/pull/2200/files

File: lib/instrumentation/redis.js (hunk 2 above)
Comment (bizob2828) [inline lib/instrumentation/redis.js:15]: we talked and agreed none of this is needed aside from the `shim.logger.warn` on line 31 as the instrumentation for v4+ is int `lib/instrumentation/@node-redis/client.js`

File: test/versioned/redis/redis-v4-legacy-mode.test.js (hunk 4 above)
Comment (bizob2828) [reply test/versioned/redis/redis-v4-legacy-mode.test.js:51]: we spoke and both agreed that these tests are valid but we will still need tests for the `.v4` functions when running v4. For v5 those are just in redis.test.js so not needed

**Review by bizob2828 — CHANGES_REQUESTED** [review]
few comments

File: test/versioned/redis/redis-v4-promises.test.js [hunk 5]
```diff
@@ -0,0 +1,273 @@
...
+ */
+
+'use strict'
+
+const test = require('node:test')
+const assert = require('node:assert')
+
+const semver = require('semver')
+const pkg = require('redis/package.json')
+if (semver.satisfies(pkg.version, '>=4.0.0 < 5.00') === false) {
```
Comment (bizob2828) [inline test/versioned/redis/redis-v4-promises.test.js:13]: i know this does the job but could be a little confusing as there's no indication that it's being skipped. in other suites we use the `{ skip: ` property of the test.

You could group the entire file in a test and all the current tests can be children.

```sh
--- a/test/versioned/redis/redis-v4-promises.test.js
+++ b/test/versioned/redis/redis-v4-promises.test.js
@@ -10,12 +10,7 @@ const assert = require('node:assert')
 
 const semver = require('semver')
 const pkg = require('redis/package.json')
-if (semver.satisfies(pkg.version, '>=4.0.0 < 5.00') === false) {
-  // This suite is testing the `.v4` object available in `redis@4` when the
-  // client has been created in "legacy mode." In short, the non-legacy API
-  // is available via `.v4` when in legacy mode.
-  process.exit(0)
-}
+const isRedis4 = semver.satisfies(pkg.version, '>=4.0.0 <5')
 
 const helper = require('../../lib/agent_helper')
 const { removeMatchedModules } = require('../../lib/cache-buster')
@@ -26,248 +21,251 @@ const { checkMetrics } = require('./utils')
 // Indicates unique database in Redis. 0-15 supported.
 const DB_INDEX = 2
 
-test.beforeEach(async function (ctx) {
-  const agent = helper.instrumentMockedAgent()
-  const redis = require('redis')
-  const client = redis.createClient({
-    legacyMode: true,
-    port: params.redis_port,
-    host: params.redis_host
+test('Redis v4 promises', { skip: !isRedis4 }, async (t) => {

```

Comment (bizob2828) [reply test/versioned/redis/redis-v4-promises.test.js:13]: That way when you run you'll see 

```sh
❯ node redis-v4-promises.test.js
﹣ Redis v4 promises (0.40025ms) # SKIP
ℹ tests 1
ℹ suites 0
ℹ pass 0
ℹ fail 0
ℹ cancelled 0
ℹ skipped 1
ℹ todo 0
ℹ duration_ms 6.722666
```

**Review by bizob2828 — APPROVED** [review]
This is fine. I'll approve but a suggestion to be more consistent with how we skip other tests
