### PR TITLE
fix: Updated Elasticsearch instrumentation to only register on v7.13.0+

### LINKED ISSUE #1809: Crash in elasticsearch instrumentation with null body.
## Description

https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentation/%40elastic/elasticsearch.js#L58

```
error.stack: "TypeError: Cannot convert undefined or null to object
	at Function.keys (<anonymous>)
	at Transport.queryParser (/mnt/ramdisk/ecom-api/node_modules/newrelic/lib/instrumentation/@elastic/elasticsearch.js:58:49)
	at DatastoreShim.parseQuery (/mnt/ramdisk/ecom-api/node_modules/newrelic/lib/shim/datastore-shim.js:456:35)
	at Transport.queryRecord (/mnt/ramdisk/ecom-api/node_modules/newrelic/lib/shim/datastore-shim.js:670:25)
	at Transport.wrapper (/mnt/ramdisk/ecom-api/node_modules/newrelic/lib/shim/shim.js:850:33)
	at IndicesApi.indicesExistsApi [as exists] (/mnt/ramdisk/ecom-api/node_modules/@elastic/elasticsearch/api/api/indices.js:361:25)
```

## Expected Behavior

No error.

## Steps to Reproduce

Calling `indicesExistsApi` in `@elastic/elasticsearch`

### PR DESCRIPTION
**Pull request by mrickard**
Added semver check to noop for ElasticSearch prior to v7.13.0.
Added defensive check on body and bulkBody params.
Added tests to verify ElasticSearch v7.13.0 and later coverage.

## How to Test

`npm run versioned elastic`

## Related Issues

Closes #1809 
Closes NR-170194.

### CODE REVIEW

File: lib/instrumentation/@elastic/elasticsearch.js [hunk 1]
```diff
@@ -130,13 +147,16 @@ function parsePath(pathString, method) {
...
+ * @param {string} pkgVersion elasticSearch version, derived from package.json
  * @returns {Function} captureInstanceAttributes method of shim
  */
-function getConnection(shim) {
-  const connectionPool = this.connectionPool.connections[0]
-  const host = connectionPool.url.host.split(':')
-  const port = connectionPool.url.port || host?.[1]
-  return shim.captureInstanceAttributes(host[0], port)
+function getConnection(shim, pkgVersion) {
+  if (semver.gte(pkgVersion, '7.16.0')) {
```
Comment (bizob2828) [inline lib/instrumentation/@elastic/elasticsearch.js:154]: is this needed? the instrumentation doesn't get loaded unless it's gte 7.16.0

File: test/versioned/elastic/elasticsearch7.tap.js [hunk 2]
```diff
@@ -0,0 +1,401 @@
...
+const urltils = require('../../../lib/util/urltils')
+const crypto = require('crypto')
+const DB_INDEX = `test-${randomString()}`
+const DB_INDEX_2 = `test2-${randomString()}`
+
+function randomString() {
+  return crypto.randomBytes(5).toString('hex')
+}
+
+test('Elasticsearch instrumentation', (t) => {
```
Comment (bizob2828) [inline test/versioned/elastic/elasticsearch7.tap.js:21]: it looks like the only differences are in some operations that in 7 need the key of body.  It may be better to just have some utility to format the request to avoid maintaining a copy of the tests with very subtle differences, thoughts?

File: lib/instrumentation/@elastic/elasticsearch.js [hunk 3]
```diff
@@ -55,9 +64,17 @@ function queryParser(params) {
     queryParam = params.querystring
   }
   // let body or bulkBody override querystring, as some requests have both
-  if (typeof params.body === 'object' && Object.keys(params.body).length > 0) {
+  if (
+    typeof params.body === 'object' &&
```
Comment (bizob2828) [inline lib/instrumentation/@elastic/elasticsearch.js:68]: we have a function in `lib/config/merge-server-config.js` isSimpleObject.  We could move that to utility and use that there and in these two places so we can have some abstract helper going forward

**Review by bizob2828 — CHANGES_REQUESTED** [review]
A few comments and questions. Nice tracking this down!

File: lib/instrumentation/@elastic/elasticsearch.js (hunk 1 above)
Comment (mrickard) [reply lib/instrumentation/@elastic/elasticsearch.js:154]: I wasn't sure if I wanted to rip that out: if we expand instrumentation to an earlier version of 7, we'd need to provide a different handling of the connection. If we don't anticipate going back that far, though, I'm happy to take it out.

Comment (bizob2828) [reply lib/instrumentation/@elastic/elasticsearch.js:154]: The 7.x we support is over 2 years old. I think we're safe and stopping there.

File: lib/instrumentation/@elastic/elasticsearch.js (hunk 3 above)
Comment (bizob2828) [reply lib/instrumentation/@elastic/elasticsearch.js:68]: up to you. just wanted to call it out that this is a valuable check

File: test/versioned/elastic/elasticsearch7.tap.js (hunk 2 above)
Comment (mrickard) [reply test/versioned/elastic/elasticsearch7.tap.js]: They're now consolidated in one file.

File: lib/instrumentation/@elastic/elasticsearch.js (hunk 3 above)
Comment (mrickard) [reply lib/instrumentation/@elastic/elasticsearch.js]: Moved into util and both elastic and merge-server config now reference it there.

File: lib/instrumentation/@elastic/elasticsearch.js [hunk 4]
```diff
@@ -17,6 +19,15 @@ const logger = require('../../logger').child({ component: 'ElasticSearch' })
  * @returns {void}
  */
 module.exports = function initialize(_agent, elastic, _moduleName, shim) {
+  const pkgVersion = shim.require('./package.json').version
+  if (semver.lt(pkgVersion, '7.13.0')) {
+    shim &&
+      shim.logger.debug(
+        `ElasticSearch support is for versions 7.16.0 and above. Not instrumenting ${pkgVersion}.`
```
Comment (villelahdenvuo) [inline lib/instrumentation/@elastic/elasticsearch.js:26]: Shouldn't this be 7.13 or above, based on the condition?

File: lib/instrumentation/@elastic/elasticsearch.js [hunk 5]
```diff
@@ -46,18 +57,17 @@ module.exports = function initialize(_agent, elastic, _moduleName, shim) {
...
-  if (typeof params.querystring === 'object' && Object.keys(params.querystring).length > 0) {
+  if (isSimpleObject(params.querystring) && Object.keys(params.querystring).length > 0) {
     queryParam = params.querystring
   }
   // let body or bulkBody override querystring, as some requests have both
-  if (typeof params.body === 'object' && Object.keys(params.body).length > 0) {
+  if (isSimpleObject(params.body) && Object.keys(params.body).length > 0) {
     queryParam = params.body
-  } else if (typeof params.bulkBody === 'object' && Object.keys(params.bulkBody).length > 0) {
+  } else if (isSimpleObject(params.bulkBody) && Object.keys(params.bulkBody).length > 0) {
```
Comment (villelahdenvuo) [inline lib/instrumentation/@elastic/elasticsearch.js:70]: With this repetition I would add `isNonEmptyObject` util:

`const isNonEmptyObject = (thing) => isSimpleObject(thing) && Object.keys(thing).length > 0`

File: lib/util/objects.js [hunk 6]
```diff
@@ -0,0 +1,11 @@
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+'use strict'
+exports = module.exports = { isSimpleObject }
+
+function isSimpleObject(thing) {
```
Comment (villelahdenvuo) [inline lib/util/objects.js:9]: Missing JSDoc. 🤓

Comment (bizob2828) [reply lib/util/objects.js:9]: Can you also write some unit tests for these new functions?

File: lib/util/objects.js [hunk 7]
```diff
@@ -0,0 +1,15 @@
...
+
+'use strict'
+exports = module.exports = { isSimpleObject, isNotEmpty }
+
+function isSimpleObject(thing) {
+  return 'object' === typeof thing && thing !== null
+}
+
+function isNotEmpty(thing) {
+  return 'object' === typeof thing && thing !== null && Object.keys(thing).length > 0
```
Comment (bizob2828) [inline lib/util/objects.js:14]:
```suggestion
  return isSimpleObject(thing) && Object.keys(thing).length > 0
```

File: test/versioned/elastic/elasticsearch.tap.js [hunk 8]
```diff
@@ -26,8 +56,14 @@ test('Elasticsearch instrumentation', (t) => {
 
   let agent
   let client
+  let pkgVersion
 
   t.before(async () => {
+    // determine version
+    const pkg = await readFile(`${__dirname}/node_modules/@elastic/elasticsearch/package.json`)
```
Comment (bizob2828) [inline test/versioned/elastic/elasticsearch.tap.js:63]: may want to put a comment as to why you can't just require the package.json

File: test/versioned/elastic/elasticsearch.tap.js [hunk 9]
```diff
@@ -26,8 +56,14 @@ test('Elasticsearch instrumentation', (t) => {
...
+    const { version: esVersion } = JSON.parse(pkg.toString())
+    pkgVersion = esVersion
```
Comment (bizob2828) [inline test/versioned/elastic/elasticsearch.tap.js:65]:
```suggestion
    ;({ version: pkgVersion } = JSON.parse(pkg.toString()))
```

File: test/versioned/elastic/elasticsearch.tap.js [hunk 10]
```diff
@@ -212,12 +250,13 @@ test('Elasticsearch instrumentation', (t) => {
...
         t.match(
           query.trace.query,
-          JSON.stringify({ query: expectedQuery }),
+          JSON.stringify({ ...expectedQuery }),
           'expected query body should have been recorded'
         )
       }
     })
   })
+  // skipping for 7.x because the client converts body to bulkBody, causing an error
```
Comment (bizob2828) [inline test/versioned/elastic/elasticsearch.tap.js:259]: this comment no longer seems relevant

**Review by bizob2828 — CHANGES_REQUESTED** [review]
A few suggestions, getting close though

File: lib/instrumentation/@elastic/elasticsearch.js (hunk 4 above)
Comment (mrickard) [reply lib/instrumentation/@elastic/elasticsearch.js]: Thank you for these suggestions, @villelahdenvuo !

File: test/versioned/elastic/elasticsearch.tap.js (hunk 9 above)
Comment (mrickard) [reply test/versioned/elastic/elasticsearch.tap.js:65]: Getting a parsing error with that.

**Review by bizob2828 — APPROVED** [review]
