### PR TITLE
fix:  Fixed event matcher to focus on properties specific to web requests (v1/ALB and v2)

### LINKED ISSUE #2857: Setting lambda handler is broken for API Gateway V2 Websocket lambda payloads since 12.8.1
Instrumenting lambda functions which process API Gateway V2 Websocket Authorizer calls causes invocation failures since 12.8.1
This was working prior to that.

## Description
Using the `newrelic.setLambdaHandler` on the handler function for an APIgatewayV2 websocket Authorizer lambda function with an event of Type `APIGatewayRequestAuthorizerEvent` causes the following runtime error

```
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read properties of undefined (reading 'pathname')",
  "stack": [
    "TypeError: Cannot read properties of undefined (reading 'pathname')",
    "    at Object.scrub (/var/task/node_modules/newrelic/lib/util/urltils.js:94:27)",
    "    at setWebRequest (/var/task/node_modules/newrelic/lib/serverless/aws-lambda.js:328:29)",
    "    at Runtime.wrappedHandler (/var/task/node_modules/newrelic/lib/serverless/aws-lambda.js:153:9)",
    "    at Runtime.runInContextCb (/var/task/node_modules/newrelic/lib/shim/shim.js:1183:20)",
    "    at AsyncLocalStorage.run (node:async_hooks:346:14)",
    "    at AsyncLocalContextManager.runInContext (/var/task/node_modules/newrelic/lib/context-manager/async-local-context-manager.js:62:38)",
    "    at Runtime.wrapped (/var/task/node_modules/newrelic/lib/transaction/tracer/index.js:208:37)",
    "    at TransactionShim.applySegment (/var/task/node_modules/newrelic/lib/shim/shim.js:1186:66)",
    "    at Runtime.transactionWrapper [as handler] (/var/task/node_modules/newrelic/lib/shim/transaction-shim.js:414:17)",
    "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
  ]
}
```

The payload shape for this use case can be seen here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-lambda-auth.html

## Expected Behavior

setting the lambda handler does not throw errors

## Steps to Reproduce

Setup a websocket APIGateway, add a lambda as an authorizer and attempt to connect to the wss address. The lambda invocation will fail with the error seen above. 
You can see tests fail if you provide the payload shape from https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-lambda-auth.html and use them in the  tests identifying APIGateway events - eg
https://github.com/newrelic/node-newrelic/blob/main/test/unit/serverless/utils.test.js#L34

## Your Environment

AWS APIGatewayV2 Websocket Authorizer nodejs lambda 

## Additional context
I think this is related to this ticket - https://github.com/newrelic/node-newrelic/pull/2780
The event payload seems to be identified as isGatewayV1Event but because there is no event.path this causes problems further on when the url pathname is expected to be present.

### PR DESCRIPTION
**Pull request by mrickard**
## Description

Customer reported an error when triggering an instrumented Lambda function via `APIGatewayRequestAuthorizerEvent`. 
This PR makes the event matching more restrictive to avoid false positives. 

## How to Test

Added event fixture to `test/unit/serverless/fixtures.js` and assertions to `test/unit/serverless/utils.test.js`. Added unit test for API Gateway V2 websocket events in `test/unit/serverless/api-gateway-v2-websocket.test.js`

## Related Issues

Closes #2857 
Closes NR-354739

### CODE REVIEW

**Review by bizob2828 — COMMENTED** [review]
This logic has been pared down quite a lot. Are we certain this won't regress on the driver for the initial refactor of this file?

File: test/unit/serverless/fixtures.js [hunk 1]
```diff
@@ -338,6 +338,60 @@ const lambaV1InvocationEvent = {
   }
 }
 
+// Event sent by API Gateway to an authorizing Lambda function. This should not be classified as a web event.
+// https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-input.html
+// Connection, Host, and Upgrade headers removed due to prettier and eslint complaints: prettier requires
```
Comment (bizob2828) [inline test/unit/serverless/fixtures.js:343]:
```suggestion
// Connection, Host, and Upgrade headers removed due to eslint complaints: it requires
```

not sure if you don't have main against this on your local branch, but prettier has been removed. it relies on neostandard which uses @stylistic for it's code formatting

**Review by bizob2828 — CHANGES_REQUESTED** [review]
one tiny suggestion on the code comments, but otherwise LGTM

**Review by bizob2828 — DISMISSED** [review]

**Review by bizob2828 — APPROVED** [review]
