### PR TITLE
DO NOT MERGE - Route/URL parameters are now stored on request.parameters.route.* attributes

### LINKED ISSUE #1574: Having a url parameter called :id in the express route will cause trace spans to break and miss their parent
## Description
When using express if you have `:id` in your url parameter it will break the transaction traceability.
it means that you will see many spans that has lost its parent.
I could not understand why this happens.
You can workaround this easily by just not using the `id` keyword and switch to something else, but this requires us to make changes in many places.

* it does not matter where in the url the `:id` will appear, as long as it appears once it will break.

* see attached screenshots to see the difference of the trace when the parameter is `:id` vs `:name`

### When using `:id` - broken
Screen Shot 2023-03-29 at 17 51 23

### When using `:name` - working
Screen Shot 2023-03-29 at 17 57 41

## Expected Behavior
should be able to use `:id`

## Steps to Reproduce

1. just create a simple route with `:id` as parameter in the url.
2. add something async like a db call.
3. view the trace in newrelic and you will see spans with lost parents

## Context
- using latest node.js newrelic agent
- using express.js version 4.x

### PR DESCRIPTION
**Pull request by jmartin4563**
## Proposed Release Notes
* **BREAKING** - Route (URL) parameters are now stored as `request.parameters.route.*` attributes on Transactions and Spans
* **BREAKING** - Removed `captureUrlParams` from `WebFrameworkShim` class

## Links
* Closes #1574 
* [PR](https://github.com/newrelic/newrelic-node-nextjs/pull/117) to update Next.js instrumentation and tests

## Details
This breaking change fixes two issues with storing request parameter related attributes:
1. Reserved attribute name collisions on spans - Reported issue, `id` is a reserved attribute name for Distributed Tracing, and spans were getting the bare route parameters added as attributes which, in conjunction with the flattening of data that occurs when we send over the wire, caused the DT parent/child span association to break.

2. Collisions between query parameters and route parameters on transactions - Discovered while investigating reported issue, having a query parameter and a route parameter named the same is a maybe strange, but valid use case. Before this change, in the event that there was a query parameter and route parameter with the same name (key), the query parameter would overwrite the route parameter. With this change, both will be respected and added as attributes.

After this change, the following becomes true:
1. Query parameters will be available as attributes prefixed with `request.parameters.*` on Transactions and Spans
2. Route parameters will be available as attributes prefixed with `request.parameters.route.*` on Transactions and Spans

Route parameters (aka url parameters) are a common feature of various web frameworks, where you can create a placeholder as part of an API route definition.

For example, given the following Express route definition and request url:
```
app.get('/api/users/:id', myMiddleware, myController)
```

```
curl http://localhost:3000/api/users/abc123?full=true
```

the route parameter is `id`, and has a value of `abc123`. This would become `request.parameters.route.id: abc123` on the Transaction and Span attributes. This example also has a query parameter of `full`, which has a value of `true`. This would become `request.parameters.full: true` on the Transaction and Span attributes.

### CODE REVIEW

File: lib/shim/webframework-shim.js [hunk 1]
```diff
@@ -117,7 +116,6 @@ WebFrameworkShim.prototype.errorHandled = errorHandled
 WebFrameworkShim.prototype.setErrorPredicate = setErrorPredicate
 WebFrameworkShim.prototype.setResponsePredicate = setResponsePredicate
 WebFrameworkShim.prototype.savePossibleTransactionName = savePossibleTransactionName
-WebFrameworkShim.prototype.captureUrlParams = captureUrlParams
```
Comment (bizob2828) [inline lib/shim/webframework-shim.js:120]: I would also include in release notes that you removed this method.  Not sure of alternative for users who may have been using this

File: lib/shim/webframework-shim.js [hunk 2]
```diff
@@ -869,10 +856,13 @@ function _recordMiddleware(shim, middleware, spec) {
     txInfo.errorHandled |= isErrorWare
 
     // Copy over route parameters onto the transaction root.
-    const params = shim.agent.config.high_security
+    let params = shim.agent.config.high_security
       ? null
       : spec.params.call(this, shim, fn, fnName, args, req)
 
+    // Route parameters are handled here, query parameters are handled in lib/transaction/index.js#_markAsWeb as part of finalization
+    params = shim.prefixRouteParameters(params)
```
Comment (bizob2828) [inline lib/shim/webframework-shim.js:864]: these attributes are always added to the middleware spans regardless of attributes.include.  This gives feature parity from before but may confuse users since they are on the request.parameters.route name space.  I know we talked about it in slack but I'm not starting to understand why these weren't prefixed.  I'm torn on the _right_ approach here but this is prob the best

File: lib/shim/shim.js [hunk 3]
```diff
@@ -2100,3 +2101,29 @@ function _es5WrapClass(shim, Base, fnName, spec, args) {
...
+ * now prefix with `request.parameter.route` to avoid collision in the event an application uses the same name for a query and route
+ * parameter. Additionally, we now store the same key on the attributes of the base segment, trace, and router span.
+ *
+ * Exported on shim to be used in our Next.js instrumentation, as that instrumentation does not follow the same pattern as all the other
+ * web frameworks we support.
+ *
+ * @param {object} params - Object containing route/url parameter key/value pairs
+ * @returns {object} the updated object, `key` will now be `request.parameters.route.key`, value remains untouched
+ */
+function prefixRouteParameters(params) {
```
Comment (bizob2828) [inline lib/shim/shim.js:2123]: I think you should add some unit tests on this since it's a public method.  I know it's getting indirectly tested but always good to find tests for methods directly too

**Review by bizob2828 — APPROVED** [review]
overall looks great. just a few suggestions on tests

File: lib/shim/webframework-shim.js (hunk 1 above)
Comment (jmartin4563) [reply lib/shim/webframework-shim.js:120]: I can re-add it, I totally spaced that this was external facing as well, I just noticed we weren't using it internally at all and naively removed it

Comment (bizob2828) [reply lib/shim/webframework-shim.js:120]: I think it's ok you remove it
