### PR TITLE
fix: Resolve logs getting blocked when an excessive payload is encoun…

### LINKED ISSUE #1998: relic agent not forwarding logs when payload size exceed
Description
We are using node js relic agent to forward logs to relic server. We found case in which logs are not forwarded to new relic server as payload size exceed and we need to restart our server to enable log forwarding again.
**Completely blocks next set of logs as relic agent retaining that logs even it is not network error** 
for your reference here is code which cause issue.
This code retain logs and not clearing batch result due to which it block next batch of logs due to merging of events in event-aggregator
image

Expected Behavior
Log should be appear in Log table except Log that has limit exceeded

Your Environment
app_name : PRODUCTION
EXPRESS: 4.18.2
apollo-server: 4.7.1
graphql: 16.6.0
Node version: 16.0.0
version: 11.5.0

### PR DESCRIPTION
**Pull request by jsumners-nr**
This PR resolves #1998.

I have tested this with an updated reproduction script:

```js
'use strict'

const newrelic = require('newrelic')
const crypto = require('node:crypto')
const { setTimeout } = require('node:timers/promises')
const xbytes = require('xbytes')
const pino = require('pino')
const log = pino(pino.destination('/dev/null'))
// const log = pino()

newrelic.startBackgroundTransaction('log-size-exceeded', async () => {
  const tx = newrelic.getTransaction()
  const allowableBytes = crypto.randomBytes(xbytes.parseSize('64KiB'))
  log.info({ bytes: allowableBytes.toString('base64') }, 'allowable log line')

  const tooManyBytes = crypto.randomBytes(xbytes.parseSize('2MiB'))
  log.info({ bytes: tooManyBytes.toString('base64') }, 'log line too big')

  // Internal method to force what _should_ happen:
  tx._transaction.logs.flush(1)
  console.log('waiting for harvest cycle...')
  let waitSecs = 10
  let int = setInterval(() => {
    if (waitSecs === 0) {
      clearInterval(int)
      return
    }
    console.log(waitSecs--)
  }, 1_000)
  await setTimeout(1000 * waitSecs)

  log.info('!!! should still get recorded')


  newrelic.shutdown({ collectPendingData: true }, () => {})
})
```

The `!!! should still get recorded` log shows up in my dashboard.

### CODE REVIEW

File: lib/collector/api.js [hunk 1]
```diff
@@ -480,10 +481,17 @@ CollectorAPI.prototype._sendData = function _sendData(method, data, callback) {
...
     // Any runtime errors should preserve the agent run.
     if (error) {
-      // TODO: log error
-      // TODO: differentiate between network (retain) and non-network (drop).
+      let retainData = true
+      if (
+        error.code &&
+        error.code === errors.ERR_CODES.NR_REMOTE_METHOD_MAX_PAYLOAD_SIZE_EXCEEDED
+      ) {
+        logger.warn('Payload size limit exceeded. Data dropped.')
```
Comment (bizob2828) [inline lib/collector/api.js:489]: we already log a warning when the error is thrown

File: test/unit/collector/api.test.js [hunk 2]
```diff
@@ -74,6 +75,51 @@ tap.test('reportSettings', (t) => {
       t.end()
     })
   })
+
+  t.test('handles excessive payload sizes without blocking subsequent sends', (t) => {
```
Comment (bizob2828) [inline test/unit/collector/api.test.js:79]: this implicitly tests the issue. not sure if it's good enough but here's what i'd do

```js
  t.test('handles excessive payload sizes without blocking subsequent sends', (t) => {
    const tstamp = 1_707_756_300_000 // 2024-02-12T11:45:00.000-05:00
    function log(data) {
      return JSON.stringify({
        level: 30,
        time: tstamp,
        pid: 17035,
        hostname: 'test-host',
        msg: data
      })
    }

    const kb512 = log(crypto.randomBytes(524_288).toString('base64'))
    const mb1 = log(crypto.randomBytes(1_048_576).toString('base64'))
    const toFind = log('find me')

    let apiHits = 0
    let sends = 0
    nock(URL)
      .persist(true)
      .post(helper.generateCollectorPath('log_event_data', RUN_ID))
      .reply(200, () => {
        apiHits += 1
      })

    agent.logs.add(kb512)
    agent.logs.send()
    agent.logs.add(mb1)
    agent.logs.send()
    agent.logs.add(toFind)
    agent.logs.send()

    agent.logs.on('finished log_event_data data send.', (t) => {
      sends++
      if (sends === 3) {
        t.equal(apiHits, 2, 'should only transmit batches that are within max limit')
      }
    })

  })
```

Comment (bizob2828) [reply test/unit/collector/api.test.js:79]: you have to call send after every log enqueue because that's when data is harvested.  so this asserts once all 3 batches have been harvested that only 2 make it to the collector and implicitly doesn't back it up like it did before your fix

File: lib/collector/errors.js [hunk 3]
```diff
@@ -0,0 +1,26 @@
+/*
+ * Copyright 2024 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+'use strict'
+
+const ERR_CODES = {
```
Comment (bizob2828) [inline lib/collector/errors.js:8]: not sure we need all of this for this ticket. i would think you're only handling the max payload exceeded

**Review by bizob2828 — CHANGES_REQUESTED** [review]

File: lib/collector/errors.js (hunk 3 above)
Comment (jsumners-nr) [reply lib/collector/errors.js:8]: I figured it might be a start to centralizing errors and establishing error codes (similar to https://github.com/fastify/fastify/blob/ffbc92c78a588e5ec6f16d20492f23b08654345f/lib/errors.js). But I'm not tied to this. I can make the payload exceeded error unique if you think that would be better.

Comment (bizob2828) [reply lib/collector/errors.js:8]: it may be fine but would prefer we keep this PR scoped to fixing the bug. especially since the other codes are errors on construction of a remote method class which only happens at boostrap of agent or when we make a request but it's all http options that we are controlling

File: lib/collector/errors.js [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+}
+module.exports.ERR_CODES = ERR_CODES
+
+module.exports.constructionError = function constructionError(msg, code) {
+  const error = new TypeError(msg)
+  error.code = code ?? ERR_CODES.NR_UNKNOWN_ERROR
+  return error
+}
+
+module.exports.generalError = function generalError(msg, code) {
```
Comment (bizob2828) [inline lib/collector/errors.js:22]: should we add unit tests for this?

File: lib/config/index.js [hunk 5]
```diff
@@ -29,7 +29,7 @@ const configDefinition = definition()
  * CONSTANTS -- we gotta lotta 'em
  */
 const AZURE_APP_NAME = 'APP_POOL_ID'
-const DEFAULT_MAX_PAYLOAD_SIZE_IN_BYTES = 1000000
+const DEFAULT_MAX_PAYLOAD_SIZE_IN_BYTES = 1_000_000
```
Comment (bizob2828) [inline lib/config/index.js:32]: 👍🏻

File: test/unit/collector/api.test.js (hunk 2 above)
Comment (bizob2828) [reply test/unit/collector/api.test.js:79]: i understand.  this is what our specifications state.  Unfortunately one bad apple will ruin the entire batch in this situation.

File: test/unit/collector/api.test.js [hunk 6]
```diff
@@ -74,6 +75,44 @@ tap.test('reportSettings', (t) => {
...
+    let sends = 0
+    const ncontext = nock(URL)
+      .post(helper.generateCollectorPath('log_event_data', RUN_ID))
+      .times(2)
+      .reply(200)
+
+    agent.logs.on('finished log_event_data data send.', () => {
+      sends += 1
+      if (sends === 3) {
+        t.equal(ncontext.isDone(), true)
```
Comment (bizob2828) [inline test/unit/collector/api.test.js:104]: very nice. didn't think of this

**Review by bizob2828 — CHANGES_REQUESTED** [review]
overall looks good. just a few comments around the extra error codes that i'd prob defer to another time, if ever

**Review by bizob2828 — APPROVED** [review]
