### PR TITLE
fix: Updated AWS Bedrock instrumentation to properly assign token counts

### LINKED ISSUE #3490: token counts not getting  assigned in bedrock
The token count calculation logic is not working in bedrock Converse API scenario.  See this [discussion](https://newrelic.slack.com/archives/G24GM9VRR/p1762188120564749?thread_ts=1761934049.259179&cid=G24GM9VRR) for more details. 

AC
- Token counts should work without any issue in `ai-monitoring/aws-bedrock-app` example app.
- Add assertions for token count within our AWS Bedrock versioned tests

### PR DESCRIPTION
**Pull request by bizob2828**
## Description
This fixed a few issues around assigning token counts:
 * adding assertions in bedrock versioned tests
 * properly handling token counts on converse, invoke model and streaming scenarios of both. We had BedrockResponse to handle all the nuance and complexity of different response shapes. I reintroduced properties to retrieve the input, output and total token counts. Basically for converse we get from body, for all others we get from headers. In the invoke model streaming, I add to headers to normalize the nuance in that use case.

I also noticed we weren't properly handling streaming of invoke model correctly. For some models, we were creating n completion messages(basically for every chunk).  Since we mock out the bedrock service, I tested with the real live models, but I didn't tests with
 - [x] titan embed
 - [x] cohere embed
 - [x] cohere(looks like no longer available, only embed models)

## How to Test

```sh
npm run unit
npm run versioned:internal:major aws-sdk-v3
```

## Related Issues
Closes #3490

### CODE REVIEW

File: lib/llm-events/aws-bedrock/chat-completion-summary.js [hunk 1]
```diff
@@ -64,7 +63,10 @@ class LlmChatCompletionSummary extends LlmEvent {
       }
       return
     }
-    setUsageTokens(this.bedrockResponse, this)
+
+    this['response.usage.prompt_tokens'] = this.bedrockResponse.inputTokenCount
```
Comment (svetlanabrennan) [inline lib/llm-events/aws-bedrock/chat-completion-summary.js]: According to the spec, these attributes should only be added if both input and output tokens exist. And omitted completely if one is missing.

File: test/versioned/aws-sdk-v3/bedrock-embeddings.test.js [hunk 2]
```diff
@@ -125,6 +125,7 @@ test.afterEach(afterEach)
     try {
       await client.send(command)
     } catch (error) {
+      console.log(error.message)
```
Comment (svetlanabrennan) [inline test/versioned/aws-sdk-v3/bedrock-embeddings.test.js]: Do we want this console.log here?

File: lib/llm-events/aws-bedrock/chat-completion-summary.js (hunk 1 above)
Comment (amychisholm03) [reply lib/llm-events/aws-bedrock/chat-completion-summary.js]: From the spec for reference:

If the agent is only able to capture data for a portion of the response usage attributes and not all of them (ex: the LLM response object only includes prompt tokens and not completion tokens), then the `token_count` attribute should be omitted from the `LlmChatCompletionMessage` events and no `response.usage.*` attributes should be added to the `LlmChatCompletionSummary` event. This is done to ensure that the agent does not send partial token counts and allows the pipeline tokenizer to handle the token counting for the message.

Comment (svetlanabrennan) [reply lib/llm-events/aws-bedrock/chat-completion-summary.js]: Also, do you want to update the embeddings event as well to match this approach?

Comment (bizob2828) [reply lib/llm-events/aws-bedrock/chat-completion-summary.js]: got it. i encapsulated all the token calculation logic into the base LLM event

**Comment by svetlanabrennan** [comment]
Also needs a PR title change since it's updating openai and genai tokens.

**Comment by bizob2828** [comment]
> Also needs a PR title change since it's updating openai and genai tokens.

It's not updating those tokens. It just centralized how tokens are extracted and assigned. I didn't have to fix anything on those libraries

File: test/versioned/aws-sdk-v3/common.js [hunk 3]
```diff
@@ -158,6 +163,12 @@ function assertChatCompletionSummary({ tx, modelId, chatSummary, error = false,
     error
   }
 
+  if (tokenUsage) {
```
Comment (bizob2828) [inline test/versioned/aws-sdk-v3/common.js]: remove this boolean as they all should have tokens counts unless it's an error
