### PR TITLE
fix: Updated MessageConsumerSubscriber to wait for consumer callback to end when it is a promise

### LINKED ISSUE #3509: Regression for async consumers with`amqplib`
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

New instrumentation of `amqplib` introduces a regression when the consumer callback is doing an async work.

```javascript
channel.consume(
      "queueName",
      async (msg) => {
            await doWork(msg);
      },
)
```

In version `13.3.3` (last before reimplementation of the instrumentation), everything happening asynchronously during the callback execution is properly reported in newrelic (eg. database accesses, ...). If the callback takes 3 seconds to perform, that duration is properly reported as the "response time".

With any version after it, including the recent `13.6.4`, it seems like the callback is not awaited, nor the transaction terminated only on eventual `ack` or `nack` calls, eg. database accesses are not reported, and the "response time" is in the microseconds scale.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

No regression (without major version bump).

Transaction to properly reflect the workload being done asynchronously on message consumption.

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

### PR DESCRIPTION
**Pull request by bizob2828**
## Description

In #3503 we updated the `MessageConsumerSubscriber` to properly end transactions that were creating during the consumption of a message.
However, we didn't have proper test coverage to ensure that if a consumption message callback was a promise that it would properly wait for the
promise to resolve before ending the transaction.  This PR fixes that.

## How to Test

```sh
npm run versioned:internal:major amqplib
```

## Related Issues
Closes #3509

### CODE REVIEW

File: lib/subscribers/message-consumer.js [hunk 1]
```diff
@@ -66,11 +66,21 @@ class MessageConsumerSubscriber extends Subscriber {
...
+   * If it's a promise, waits for it to resolve before ending transaction.
+   * This ensures that the transaction stays active until the promise resolves.
+   * @param {object} data the data associated with the `asyncEnd` event
    */
-  asyncEnd() {
+  asyncEnd(data) {
     const ctx = this.agent.tracer.getContext()
-    ctx?.transaction?.end()
+    const result = data.cbResult
+    if (result instanceof Promise) {
```
Comment (jsumners-nr) [inline lib/subscribers/message-consumer.js]: It could be a thenable or even some random non-native `Promise` implementation. We should instead:

```suggestion
    if (typeof result.then === 'function') {
```

File: lib/subscribers/message-consumer.js [hunk 2]
```diff
@@ -66,11 +66,21 @@ class MessageConsumerSubscriber extends Subscriber {
...
+      result.finally(() => {
```
Comment (jsumners-nr) [inline lib/subscribers/message-consumer.js]: 😕 if we accept my above suggestion, then we don't have a guarantee that `.finally` is available. In that case, we should probably do:

```js
if (typeof result.then === 'function') {
	const p = Promise.resolve(result)
	p.finally(() => { /* stuff */ })
}
```

-----

<details>
<summary>Example</summary>

```js
'use strict'

const thenable = {
  then(cb) {
    cb(1764)
  }
}

main()
  .then(() => { console.log('main done') })
  .catch((error) => { console.log('main error: ', error) })

async function main () {
  const p = Promise.resolve(thenable)
  p
    .then((input) => {
      console.log(Math.sqrt(input))
    })
    .finally(() => { console.log('thenable resolved') })

  await p
}
```

</details>

File: lib/subscribers/message-consumer.js (hunk 1 above)
Comment (bizob2828) [reply lib/subscribers/message-consumer.js]: true. I'll update

**Review by jsumners-nr — APPROVED** [review]
