### PR TITLE
fix: Updated `api.recordLogEvent` to no longer truncate the message key in log event

### LINKED ISSUE #2921: Manual logs are truncated when they shouldn't
## How logs should be truncated

According to the [docs](https://docs.newrelic.com/docs/logs/troubleshooting/log-message-truncated/):

>This occurs because the logs datastore in New Relic limits the field length to 4,094 characters. Any data longer than that is truncated during ingestion.

So, the _field length_ is limited, not the entire log message. The tips to fix this are:

- > Parse your log message into shorter key/value pairs.
- > Use JSON as an output format instead of plain text. JSON log messages will automatically be parsed into key/value pairs, which makes it much less likely to hit the character limit.

## The problems

There are two problems with logs created with `recordLogEvent()`:

1. **Log messages are truncated at 1024** characters, not 4096 as stated:

   https://github.com/newrelic/node-newrelic/blob/c7ae8befafa4c91fab6804cd95e20f5a93546ea4/lib/util/application-logging.js#L8-L9

2. **Log messages are truncated _before_ JSON parsing**, not after as stated. This causes a lot of log messages to be truncated, even though they are both well under 4096 characters total, and each field is under 1024 characters.

   https://github.com/newrelic/node-newrelic/blob/c7ae8befafa4c91fab6804cd95e20f5a93546ea4/api.js#L516

To fix this, I believe the line performing the truncation above should be removed completely. Even if the log is too large, the back-end alone should handle the truncation. Otherwise, the rest of the log, which would become a `blob`, is lost instead:

  > The first 4,094 characters in a log message are stored as a string. The next 128,000 bytes are stored as a blob.

Also, parsing the message & performing a correct truncation client-side would be very expensive performance-wise. This is why the message is expected to be a JSON string and not an object that is then transformed with `JSON.stringify`, as most logging libraries produce JSON strings with their own fast algorithms instead of `JSON.stringify`.

I'm happy to make a quick PR to fix this if all is OK.

### PR DESCRIPTION
**Pull request by rChaoz**
See the related issue: fixes #2921 

In short: `logEvent.message` can either be a simple string message, in which truncating is OK, but it can also be the full JSON log (stringified), in which case it mustn't be truncated.

### CODE REVIEW

File: api.js [hunk 1]
```diff
@@ -513,7 +513,6 @@ API.prototype.recordLogEvent = function recordLogEvent(logEvent = {}) {
     )
     return
   }
-  logEvent.message = applicationLogging.truncate(logEvent.message)
```
Comment (bizob2828) [inline api.js:516]: can you please add a test with a very long message `test/unit/api/api-record-log-events.test.js`

**Review by bizob2828 — CHANGES_REQUESTED** [review]

**Review by bizob2828 — DISMISSED** [review]

File: test/unit/api/api-record-log-events.test.js [hunk 2]
```diff
@@ -156,6 +156,23 @@ test('Agent API - recordCustomEvent', async (t) => {
...
+
+  await t.test('it works with large JSON log messages', (t, end) => {
+    const { agent, api } = t.nr
+    const json = JSON.stringify({
+      message: message.repeat(100),
+      nested: {
+        prop1: 123,
+        prop2: 'a string',
+      },
+      array: Array.from({ length: 1000 }, i => 'item number ' + i),
```
Comment (bizob2828) [inline test/unit/api/api-record-log-events.test.js:168]:
```suggestion
      array: Array.from({ length: 1000 }, (_, i) => 'item number ' + i),
```

**Review by bizob2828 — APPROVED** [review]
thanks for adding the test!

**Comment by bizob2828** [comment]
@rChaoz this PR landed in [12.14.0](https://github.com/newrelic/node-newrelic/releases/tag/v12.14.0), please upgrade.
