### PR TITLE
fix: Updated `mysql2` instrumentation to work with 3.11.5+

### LINKED ISSUE #2810: mysql2@3.11.5 instrumentation is broken
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Apparently we were relying on the fact that the callback based code was a circular reference in mysql2. This was tweaked in https://github.com/sidorares/node-mysql2/pull/3081/files.  

## Steps to Reproduce
```sh
cd test/versioned/mysql2
npm i mysql2@3.11.5 generic-pool@2.4 --no-save --no-package-lock
node promises.test.js
```

## Expected Result 
Tests pass

## Actual Result
Tests are not passing

### PR DESCRIPTION
**Pull request by bizob2828**
## Description

Turns out we were relying on the fact that the `msyql2/index.js` was a circular reference for the `mysql2/promises` interface.  This was updated in https://github.com/sidorares/node-mysql2/pull/3081/files.  I also noticed that the versioned tests were configuring the sql tracing in the config file and at times wasn't sticking. So I moved those to be explicit in the tests that need that configuration.

## How to Test

```sh
npm run versioned:internal mysql2
npm run versioned:internal mysql
```

## Related Issues
Closes #2810

### CODE REVIEW

**Review by jsumners-nr — DISMISSED** [review]
Thank you. I was really confused by our original `promiseInitialize` function. It was loading the callback based interface, so I thought we were wrapping that up in some sort of way. It makes much more sense to skip that.

**Comment by bizob2828** [comment]
> Thank you. I was really confused by our original `promiseInitialize` function. It was loading the callback based interface, so I thought we were wrapping that up in some sort of way. It makes much more sense to skip that.

Yea so the mysql root required the `index` ask callback initialization.  But the mysql2 refactor no longer requires 1 package but split up the innards into relevant functions. This just updates the instrumentation to wrap the exported functions and accesses the callback based functions as properties on connection, pool and pool cluster

File: lib/instrumentation/mysql/mysql.js [hunk 1]
```diff
@@ -11,63 +11,116 @@ const symbols = require('../../symbols')
...
+/**
+ * Used to instrument `mysql2/promise`
+ *
+ * @param {Shim} shim instance of shim
+ * @param {object} mysql2 package to instrument
+ */
+function promiseInitialize(shim, mysql2) {
+  shim.setDatastore(shim.MYSQL)
+  shim[symbols.wrappedPoolConnection] = false
+  shim.wrap(
```
Comment (jsumners-nr) [inline lib/instrumentation/mysql/mysql.js:39]: Should this, and the others in this change set, be `shim.wrapReturn`?

Comment (bizob2828) [reply lib/instrumentation/mysql/mysql.js:39]: no because in this case we have the function we need to wrap directly. In the callback style it's what gets returned from the `createConnection`, `createPool`, etc
