### PR TITLE
Fix pino crash

### LINKED ISSUE #1328: Custom level in pino seems to be crashing
Hi, I'm using pino with custom level and when bumping newrelic from 8.5.2 to 9.0.0 it crashes on this line with cannot call toUpperCase on undefined :

```js
metrics.getOrCreateMetric(LOGGING.LEVELS[level.toUpperCase()]).incrementCallCount()
```

See: https://github.com/newrelic/node-newrelic/commit/42b3ea9e984cc8d07dc04187262b6066b9d0d235

Here is my pino configuration :

```js
pino({
		transport: {
			target: '@serdnam/pino-cloudwatch-transport',
			options: {
				logGroupName: process.env.LOGGING_GROUP_NAME,
				logStreamName: process.env.LOGGING_STREAM_NAME,
				awsRegion: 'eu-west-3',
				awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID,
				awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
				interval: 2000,
			},
		},
		base: { hostname: os.hostname() },
		depthLimit: 3,
		timestamp: false,
		useLevelLabels: true,
		level: process.env.LOG_LEVEL || 'debug',
		enabled: process.env.NODE_ENV !== 'test',
		customLevels: {
			http: 35, // above info
		},
		formatters: {
			level(level) {
				return { level };
			},
		},
	})
```

Here is my newrelic configuration :

```js
/**
 * New Relic agent configuration.
 *
 * See lib/config/default.js in the agent distribution for a more complete
 * description of configuration variables and their potential values.
 */
exports.config = {
	/**
	 * Array of application names.
	 */
	app_name: [process.env.NEW_RELIC_APPLICATION_NAME],
	/**
	 * Your New Relic license key.
	 */
	license_key: process.env.NEW_RELIC_LICENSE_KEY,

	/**
	 * This setting controls distributed tracing.
	 * Distributed tracing lets you see the path that a request takes through your
	 * distributed system. Enabling distributed tracing changes the behavior of some
	 * New Relic features, so carefully consult the transition guide before you enable
	 * this feature: https://docs.newrelic.com/docs/transition-guide-distributed-tracing
	 * Default is true.
	 */
	distributed_tracing: {
		/**
		 * Enables/disables distributed tracing.
		 *
		 * @env NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
		 */
		enabled: true,
	},
	logging: {
		/**
		 * Level at which to log. 'trace' is most useful to New Relic when diagnosing
		 * issues with the agent, 'info' and higher will impose the least overhead on
		 * production applications.
		 */
		level: 'info',
	},
	/**
	 * When true, all request headers except for those listed in attributes.exclude
	 * will be captured for all traces, unless otherwise specified in a destination's
	 * attributes include/exclude lists.
	 */
	allow_all_headers: true,
	error_collector: {
		enabled: true,
		ignore_status_codes: [401, 403, 404],
	},
	application_logging: {
		forwarding: {
			enabled: false,
		},
		local_decorating: {
			enabled: true,
		},
	},
	attributes: {
		/**
		 * Prefix of attributes to exclude from all destinations. Allows * as wildcard
		 * at end.
		 *
		 * NOTE: If excluding headers, they must be in camelCase form to be filtered.
		 *
		 * @env NEW_RELIC_ATTRIBUTES_EXCLUDE
		 */
		exclude: [
			'request.headers.cookie',
			'request.headers.authorization',
			'request.headers.proxyAuthorization',
			'request.headers.setCookie*',
			'request.headers.x*',
			'response.headers.cookie',
			'response.headers.authorization',
			'response.headers.proxyAuthorization',
			'response.headers.setCookie*',
			'response.headers.x*',
		],
	},
};
```

### PR DESCRIPTION
**Pull request by billouboq**
## Proposed Release Notes
 * Handled setting the logging metric name to `UNKNOWN` when using custom log levels in pino and/or winston.

## Links
Closes #1328 

## Details

Don't know if that's the right way to do it since I'm not sure about the codebase, but atleast it's not crashing anymore.

If there is other changes to make don't hesitate.

Should fix https://github.com/newrelic/node-newrelic/issues/1328

### CODE REVIEW

File: lib/util/application-logging.js [hunk 1]
```diff
@@ -82,8 +82,10 @@ utils.isLogForwardingEnabled = function isLogForwardingEnabled(config, agent) {
  * @param {object} metrics metrics module
  */
 utils.incrementLoggingLinesMetrics = function incrementLoggingLinesMetrics(level, metrics) {
+  const logginLevelMetric = level ? LOGGING.LEVELS[level.toUpperCase()] : LOGGING.LEVELS.UNKNOWN
```
Comment (bizob2828) [inline lib/util/application-logging.js:85]:
```suggestion
  const loggingLevelMetric = level ? LOGGING.LEVELS[level.toUpperCase()] : LOGGING.LEVELS.UNKNOWN
```

File: lib/util/application-logging.js [hunk 2]
```diff
@@ -82,8 +82,10 @@ utils.isLogForwardingEnabled = function isLogForwardingEnabled(config, agent) {
...
+
   metrics.getOrCreateMetric(LOGGING.LINES).incrementCallCount()
-  metrics.getOrCreateMetric(LOGGING.LEVELS[level.toUpperCase()]).incrementCallCount()
+  metrics.getOrCreateMetric(logginLevelMetric).incrementCallCount()
```
Comment (bizob2828) [inline lib/util/application-logging.js:88]:
```suggestion
  metrics.getOrCreateMetric(loggingLevelMetric).incrementCallCount()
```

File: lib/metrics/names.js [hunk 3]
```diff
@@ -273,7 +273,8 @@ const LOGGING = {
     WARN: `${LOGGING_LINES_PREFIX}/WARN`,
     ERROR: `${LOGGING_LINES_PREFIX}/ERROR`,
     DEBUG: `${LOGGING_LINES_PREFIX}/DEBUG`,
-    TRACE: `${LOGGING_LINES_PREFIX}/TRACE`
+    TRACE: `${LOGGING_LINES_PREFIX}/TRACE`,
+    UNKNOWN: `${LOGGING_LINES_PREFIX}/UNKNOWN`
```
Comment (bizob2828) [inline lib/metrics/names.js:277]: thanks! this is actually in our specification and we overlooked it

File: lib/util/application-logging.js [hunk 4]
```diff
@@ -82,8 +82,10 @@ utils.isLogForwardingEnabled = function isLogForwardingEnabled(config, agent) {
  * @param {object} metrics metrics module
  */
 utils.incrementLoggingLinesMetrics = function incrementLoggingLinesMetrics(level, metrics) {
```
Comment (bizob2828) [inline lib/util/application-logging.js:84]: I'm going to add a unit test for this as well once this lands

File: test/versioned/pino/pino.tap.js [hunk 5]
```diff
@@ -246,17 +276,29 @@ tap.test('Pino instrumentation', (t) => {
...
+            http: 35
+          }
+        },
+        stream
+      )
+
       helper.runInTransaction(agent, 'pino-test', async () => {
         const logLevels = {
           debug: 20,
+          http: 4, // this one is a custom level
```
Comment (bizob2828) [inline test/versioned/pino/pino.tap.js:293]: very nice, thanks for adding this integration test case!

**Review by bizob2828 — CHANGES_REQUESTED** [review]
Overall looks good.  The variable name should be changed though per my suggestions.  Thanks for taking the time to submit this PR 🙏🏻

**Review by bizob2828 — APPROVED** [review]
