### PR TITLE
mongo v4 fixes

### LINKED ISSUE #806: Add support for mongodb ^4.0.0
## Feature Description
Add support for `mongodb` module >=v4.0.0. `mongodb` `collectoin-find` and `collection-common` versioned tests were failing for v4.0.0.

### PR DESCRIPTION
**Pull request by bizob2828**
## Proposed Release Notes
 * Added necessary instrumentation to support v4 of mongodb

## Links
Closes #806 

## Details
I refactored the mongo instrumentation to make it easier to read.  It was clear as versions changed new logic was just bolted on.  I grouped the necessary instrumentation by 3 different files and added a common file for shared code.  I also ran the versioned tests on all minor versions and check code coverage and determined there were a few blocks of dead code due to changes in version we no longer support.  We never run our domain socket tests in CI, which has led to failure in tests.  I was running mongod 4.4.5 locally and had a few failures for a variety of reasons.  Mostly due to the fact that they removed some commands, or added extra security around password hashes.  To test with domain sockets locally:

 * [Install mongod](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/)
 * start mongo: `mongodb`
 * `npm run versioned-tests mongodb`

### CODE REVIEW

File: bin/run-versioned-tests.sh [hunk 1]
```diff
@@ -5,7 +5,7 @@
 
 set -x
 
-VERSIONED_MODE="${VERSIONED_MODE:---major}"
+VERSIONED_MODE="${VERSIONED_MODE:---minor}"
```
Comment (bizob2828) [inline bin/run-versioned-tests.sh:8]: revert this, i was just doing this to make sure my changes worked on all minor versions

File: package.json [hunk 2]
```diff
@@ -135,6 +135,7 @@
     "unit": "rm -f newrelic_agent.log && time tap --test-regex='(\\/|^test\\/unit\\/.*\\.test\\.js)$' --timeout=180 --no-coverage --reporter classic",
     "update-cross-agent-tests": "./bin/update-cats.sh",
     "versioned-tests": "./bin/run-versioned-tests.sh",
+    "versioned-tests-cov": "nyc --reporter=lcov --reporter=html ./bin/run-versioned-tests.sh",
```
Comment (bizob2828) [inline package.json:138]: remove this, was just using it to verify coverage

File: package.json [hunk 3]
```diff
@@ -186,6 +187,7 @@
     "mongodb": "^3.3.3",
     "mysql": "*",
     "nock": "11.8.0",
+    "nyc": "^15.1.0",
```
Comment (bizob2828) [inline package.json:190]: remove this, was just using it to verify coverage

File: .eslintrc.js [hunk 4]
```diff
@@ -5,7 +5,7 @@ module.exports = {
     "browser": false
   },
   "parserOptions": {
-    "ecmaVersion": 6
+    "ecmaVersion": 11
```
Comment (bizob2828) [inline .eslintrc.js:8]: had to bump this as I used object spread

Comment (michaelgoin) [reply .eslintrc.js:8]: Just a word of historical knowledge...

The team traditionally avoided bumping the ecmaVersion beyond what was safe to use for the minimum version of Node we support. This was an additional layer of protection in case a language feature ended up used on a path that was not well tested for some reason so we would not see a crash in our CI for that Node version. As such, usually the test eslintrc got bumped as far as needed to test various language features and the standard one lagged behind. Spread should be covered regardless, I'm guessing ecmascript 9 or 10 is what matches up to Node 12+ mostly.

In reality, the risk of this is likely pretty low these days. We do have some blind spots testing wise but mostly have pretty good coverage. As such, I'm fine landing this.

Where we could get into trouble is with the usage of `Promise.allSettled`, `??`, and `?.` according to: https://node.green/#ES2020. We still need to avoid those in non-test code.

**Review by michaelgoin — APPROVED** [review]

File: .eslintrc.js (hunk 4 above)
Comment (bizob2828) [reply .eslintrc.js:8]: yea. we could go up to 19 per node.green.

**Review by michaelgoin — APPROVED** [review]
