### PR TITLE
fix: Ensure opts.headers is defined in request instrumenting

### LINKED ISSUE #1925: Crash when instrumenting request with null headers
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
When instrumenting some older libraries, it appears that newrelic does not properly handle things and causes a crash. In this case, the instrumentation is happening where `opts.headers` is `null` instead of an object or `undefined`. `null` does not get handled properly by defaulting and throws an error when it checks for the existence of specific headers.

image

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
The system should handle `opts.headers` being `null` the same as `undefined` and thus properly default it to an empty object for handling.
[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
It's difficult to reproduce as the situation is very specifically dependent on both the system we use and the way we use it (which I do not feel comfortable sharing here).
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

### PR DESCRIPTION
**Pull request by OuranosSkia**
## Description
This fixes a bug where if `opts.headers` is `null`, it is not handled by further down functions and causes a crash.

## How to Test
Unfortunately, the situations in which this is reproduced are very specific to a flow that I have difficulty artificially reproducing. I am applying this fix as a technical code fix purely based on the way that it is crashing.

## Related Issues
Fixes #1925

### CODE REVIEW

File: lib/instrumentation/core/http-outbound.js [hunk 1]
```diff
@@ -138,6 +138,8 @@ function instrumentRequest(agent, opts, makeRequest, hostname, segment) {
   const transaction = segment.transaction
   const outboundHeaders = Object.create(null)
 
+  opts.headers = opts.headers || {};
```
Comment (bizob2828) [inline lib/instrumentation/core/http-outbound.js:141]: Can you please write a unit test for this?

Here's one that exhibits the issue.

```js
  t.test('should not crash when req.headers is null', (t) => {
    const req = new events.EventEmitter()
    helper.runInTransaction(agent, function (transaction) {
      const path = '/asdf'
      const name = NAMES.EXTERNAL.PREFIX + HOSTNAME + ':' + PORT + path

      instrumentOutbound(agent, { headers: null, host: HOSTNAME, port: PORT }, makeFakeRequest)
      t.equal(transaction.trace.root.children[0].name, name)

      function makeFakeRequest() {
        req.path = '/asdf?a=b&another=yourself&thing&grownup=true'
        return req
      }
    })
    t.end()
  })
```

You should put it in `/test/unit/instrumentation/http/outbound.test.js`

**Review by bizob2828 — CHANGES_REQUESTED** [review]
Thanks for the fix, sorry for the troubles here.

File: lib/instrumentation/core/http-outbound.js (hunk 1 above)
Comment (OuranosSkia) [reply lib/instrumentation/core/http-outbound.js]: Thanks for this! I had actually looked for a test to update, but was looking in `/test/unit/instrumentation/core` and didn't see one. I added the test and will @ you once I see things have passed.

**Review by bizob2828 — APPROVED** [review]

File: lib/instrumentation/core/http-outbound.js (hunk 1 above)
Comment (bizob2828) [reply lib/instrumentation/core/http-outbound.js]: I tweaked it slightly to be more specific. I didn't mean for you to copy/paste but use for inspiration.  Anyways, we appreciate the fix 🙏🏻

Comment (OuranosSkia) [reply lib/instrumentation/core/http-outbound.js]: Oh, sorry! Haha. Thanks for the tweak. I should have paid more attention to what you were proposing.
