### PR TITLE
fix: Updated `app.use` or `router.use` Express instrumentation to properly wrap all middleware defined

### LINKED ISSUE #3518: Agent crash when defining an array of middleware to `router.use`
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When upgrading to newrelic @13.6.0, our code started breaking with the following exception:
```
/Users/schmidtt/w/video-api2/node_modules/newrelic/lib/subscribers/express/use.js:28
    if (fn.lazyrouter || fn.name === 'mounted_app') {
           ^
TypeError: Cannot read properties of undefined (reading 'lazyrouter')
    at ExpressUseSubscriber.handler (/Users/schmidtt/w/video-api2/node_modules/newrelic/lib/subscribers/express/use.js:28:12)
    at handler (/Users/schmidtt/w/video-api2/node_modules/newrelic/lib/subscribers/base.js:234:27)
    at node:diagnostics_channel:92:17
    at Channel.runStores (node:diagnostics_channel:177:12)
    at TracingChannel.traceSync (node:diagnostics_channel:333:18)
    at Function.use (/Users/schmidtt/w/video-api2/node_modules/express/lib/router/index.js:287:29)
    at Object.<anonymous> (/Users/schmidtt/w/video-api2/src/routes/api/index.ts:44:8)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1706:14)
    at Module.wrappedCompile [as _compile] (/Users/schmidtt/w/video-api2/node_modules/@apm-js-collab/tracing-hooks/index.js:45:27)
    at Object..js (node:internal/modules/cjs/loader:1839:10)
```

I tracked the problem down to this change: https://github.com/newrelic/node-newrelic/pull/3424

It seems to be causing an incompatibility with some [error handling middleware](https://github.com/taschmidt/newrelic-use-bug/blob/main/middleware.ts) of ours so it's entirely possible we may need to change assumptions in there.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

It shouldn't throw an exception.

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

Pull down [this repo](https://github.com/taschmidt/newrelic-use-bug) and run `npx tsx --env-file .env ./app.ts`.

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

Node v22.21.1
MacOS 15.7.2

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Node version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

### PR DESCRIPTION
**Pull request by bizob2828**
## Description

We weren't properly handling all the ways you can define middleware on `.use` both with express and router.  This PR resolves this by iterating over all the arguments and wrapping any functions that are defined.

## How to Test

```sh
npm run versioned:internal express
```

## Related Issues

Closes #3518

### CODE REVIEW

File: lib/subscribers/express/use.js [hunk 1]
```diff
@@ -14,32 +14,82 @@ class ExpressUseSubscriber extends ExpressSubscriber {
...
+   * @param {object} params to function
+   * @param {Array} params.middlewares array of middleware to wrap
+   * @param {string|null} params.route route defined in `.use`
+   * @param {string} params.routeName route name for segment naming
+   */
+  wrapAllMiddleware({ middlewares, route, routeName }) {
+    for (let i = 0; i < middlewares.length; i++) {
+      const middleware = middlewares[i]
+      if (Array.isArray(middleware)) {
+        this.wrapAllMiddleware({ middlewares: middleware, route })
```
Comment (jsumners-nr) [inline lib/subscribers/express/use.js:44]: Should there be a `continue` statement here? Or do we really expect the rest of the loop to continue after the recursive call?

Comment (bizob2828) [reply lib/subscribers/express/use.js:44]: yea, we can't break out of the loop. You could have:

```js
app.use([mw1, mw2], mw3, [mw4, mw5])
```
