### PR TITLE
fix: Updated MessageProducerSubscriber to properly set the sampled flag on traceparent

### LINKED ISSUE #3504: Sampled flag in message producer not properly getting set
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I noticed that the sampled flag was always getting set to `00`.  This is because we checked `transaction.sampled` to decide whether to set flag to `01`.  The sampled flag is null until priority is calculated.  We lacked explicit assertions on the sampled flag in `traceparent` header in amqplib.  

## Expected Behavior

Set sampled flag to `01` if transaction is sampled, otherwise `01`.

## Steps to Reproduce
Send a message with amqplib, observe outbound headers.

### PR DESCRIPTION
**Pull request by bizob2828**
## Description
This was found while digging into #3502. I noticed the traceparent sampled flag was always `00`.  This currently has 0 impact on agents that haven't set `remote_parent_sampled` or `remote_parent_not_sampled` to `always_on` or `always_off`. This is because sampling in a downstream service is determined by the `tracestate` header which sets the sampled to the `transaction.sampled` flag after the sampling and priority have been calculated.  In our MessageProducerSubscriber we were checking `transaction.sampled` which is to to null until a priority has been calculated which is typically done in `insertDistributedTraceHeaders`. This is being short-circuited because we manually pass in the spanId, traceid and sampling flag. The reason we pass it in is because the headers are injected before the outgoing message publish happens. Typically this API is being called during(right before publish), but not in the new subscriber based model.  

Long story short, the proper way to set the sampled flag is to call `transaction.isSampled()` which calculates a priority and assigns sampled flag if not already done. This also adds explicit assertions in amqplib tests to assert the sampled flag is correct in the traceparent. 

## Related Issues
Closes #3504

### CODE REVIEW

File: lib/subscribers/base.js [hunk 1]
```diff
@@ -363,7 +363,7 @@ class Subscriber {
     if (distributedTracingEnabled) {
       // we have to pass in traceId, segment id, and hard code traceFlags to 1
       // because we're inserting headers right before the original function is bound.
-      const traceFlags = tx.sampled === true ? 1 : 0
+      const traceFlags = tx.isSampled() === true ? 1 : 0
```
Comment (jsumners-nr) [inline lib/subscribers/base.js:366]: From your description, this makes sense. One of the benefits to the way we are doing things in new code is that we tend to define getters which make this less likely to occur. The internal state variable, `tx.sampled` in this case, isn't exposed, thus forcing usage of the "does it right" path.
