### PR TITLE
fix: Updated instrumentation registration to allow for instrumenting of a local file that does not exist within node_modules. You must pass in `absolutePath` with the absolute path to the file that is being instrumented along with the moduleName which in this case is just the file name without the extension

### LINKED ISSUE #1973: Unable to instrument files that are not an npm package
## Description
Prior to [v11.0.0](https://github.com/newrelic/node-newrelic/releases/tag/v11.0.0) of the agent, you could use the API `instrument`, `instrumentMessages`, etc to instrument any file.  The moduleName had to be the first time the package is required.  In v11.0.0 we switched to use `require-in-the-middle` to instrument CommonJS modules.  

In the v11.0.0 changelog we did call out: "You can no longer instrument files that are not within a node_module unless you provide an absolute path to the file when registering the instrumentation."  However, that's not entirely possible.  

## Expected Behavior
Provide ability to instrument a file that's not within a 3rd party package.

You should see this in the output of repro app

```sh
[NEWRELIC] instrumenting nifty-messages
[NEWRELIC] instrumenting method 'publish'
[NEWRELIC] instrumenting method 'purge'
[NEWRELIC] instrumenting callbacks of method 'getMessage'
[NEWRELIC] instrumenting callbacks of method 'subscribe'
```

## Steps to Reproduce
 1. Clone this [repo](https://github.com/newrelic/newrelic-node-examples/tree/main/messaging-app)
 2. Follow readme but upgrade to latest agent `npm i newrelic@latest`
 3. Run `npm start`

## Additional context
This probably doesn't affect any customers.  It just makes it easier for us to show how to use the instrument API methods by building some contrived "module" but have it live within the application.

### PR DESCRIPTION
**Pull request by bizob2828**
## Description

We tried to add instrumentation for local files. This was done in [messaging-app] but was using v9.x of the agent.  In v11.0.0 we now use `require-in-the-middle` for instrumenting CJS, which requires additional work to instrument files that are not within a 3rd party module.  This PR fixes that by providing a new `absolutePath` key:

```js
'use strict'

const newrelic = require('newrelic')
const niftyPath = require.resolve('./nifty-messages')

newrelic.instrumentMessages({ absolutePath: niftyPath, moduleName: 'nifty-messages', onRequireHandler)
```

## How to Test

`node test/integration/module-loading/module-loading.tap.js` adds a new test for this.

## Related Issues
Closes #1973

### CODE REVIEW

File: lib/shimmer.js [hunk 1]
```diff
@@ -398,11 +398,12 @@ const shimmer = (module.exports = {
 
     if (!registeredInstrumentation) {
       shimmer.registeredInstrumentations[opts.moduleName] = []
+      const pkgHook = opts.absolutePath || opts.moduleName
```
Comment (bizob2828) [inline lib/shimmer.js:401]: put a comment explaining this nuance

**Review by svetlanabrennan — APPROVED** [review]
